app <- ShinyDriver$new("../../", seed = 1234, loadTimeout = 1e+05)
app$snapshotInit("test_2")

app$setInputs(RLBase = "Samples")
app$setInputs(rmapSampsTabset = "Annotation")
app$snapshot()
app$setInputs(rmapSampsTabset = "RLFS")
app$snapshot()
app$setInputs(select_prediction_NEG = FALSE)
app$setInputs(selectRNH = TRUE)
app$setInputs(selectMode = c("DRIPc", "DRIP", "qDRIP", "sDRIP", "RDIP"))
app$setInputs(selectMode = c("DRIPc", "DRIP", "qDRIP", "sDRIP", "RDIP", "DRIVE"))
app$setInputs(selectMode = c("DRIPc", "DRIP", "qDRIP", "sDRIP", "RDIP", "DRIVE", "R-ChIP"))
app$setInputs(selectMode = c("DRIPc", "DRIP", "qDRIP", "sDRIP", "RDIP", "DRIVE", "R-ChIP", "MapR"))
app$setInputs(selectMode = c("DRIPc", "DRIP", "qDRIP", "sDRIP", "RDIP", "DRIVE", "R-ChIP", "MapR", "RNH-CnR"))
app$setInputs(selectMode = c("DRIPc", "DRIP", "qDRIP", "sDRIP", "RDIP", "DRIVE", "R-ChIP", "MapR", "RNH-CnR", "RR-ChIP"))
app$snapshot()
app$setInputs(RLBase = "R-Loop DB")
app$setInputs(rloopStats = "Expression")
app$snapshot()
