env:
  RENV_PATHS_ROOT: ~/.local/share/renv
  UBUNTU_VERSION: 20.04
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-${{ UBUNTU_VERSION }}
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.config.r }}
    - name: Install Sys dependencies
      run: |
        Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
        sysreqs=$(Rscript -e "apt_get_install('renv.lock', distribution = 'ubuntu', release = '${{ UBUNTU_VERSION }}')")
        echo $sysreqs
        sudo apt-get update
        sudo eval "$sysreqs"
    - name: Cache packages
      uses: actions/cache@v1
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    - name: Restore packages
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        options(repos = c(RSPM = "https://packagemanager.rstudio.com/all/latest"))
        renv::restore()
    - name: Run tests
      shell: Rscript {0}
      run: |
        shiny::runTests(".", assert = TRUE)
